apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: modelcar-pipelinerun
spec:
  pipelineRef:
    name: modelcar-pipeline
  timeout: 3h  # Add a 2-hour timeout
  params:
    - name: HUGGINGFACE_MODEL
      value: "ibm-granite/granite-3.2-2b-instruct"
    - name: OCI_IMAGE
      value: "quay.io/hayesphilip/modelcar-granite-3.2-2b-instruct"
    - name: HUGGINGFACE_ALLOW_PATTERNS
      value: "*.safetensors,*.json,*.txt"
    - name: COMPRESS_MODEL
      value: "true"
    - name: MODEL_NAME
      value: "granite-3.2-2b-instruct"
    - name: MODEL_VERSION
      value: "1.0.0"
    - name: SKIP_TASKS
      value: "cleanup-workspace,pull-model-from-huggingface,compress-model,process,build-and-push-modelcar"
    - name: MODEL_REGISTRY_URL
      value: "https://registry-rest.apps.dev.xxx"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: modelcar-storage
    - name: quay-auth-workspace
      secret:
        secretName: quay-auth
  podTemplate:
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
    nodeSelector:
      nvidia.com/gpu.present: "true"
